# Generated by Django 5.2.4 on 2025-07-20 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyWeather',
            new_name='MonthlyWeather',
        ),
    ]
