# Generated by Django 5.2.4 on 2025-07-22 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_weatherimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeatherImage',
        ),
    ]
