# Generated by Django 5.2.4 on 2025-11-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_user_weatherimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyWeather1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('date', models.DateField()),
                ('avg_temp', models.FloatField()),
            ],
            options={
                'unique_together': {('lat', 'lon', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='MonthlyWeather',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='WeatherImage',
        ),
    ]
