# Generated by Django 5.2.4 on 2025-11-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_monthlyweather_delete_monthlyweather1'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('clothing', models.TextField()),
                ('activities', models.TextField()),
                ('health', models.TextField()),
                ('travel', models.TextField()),
            ],
            options={
                'unique_together': {('city', 'date')},
            },
        ),
    ]
